name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Prisma CLI
        run: npm install -g prisma

      - name: Show installed dependencies
        run: npm list

      - name: Grant execute permission to vitest
        run: chmod +x node_modules/.bin/vitest

      - name: Generating client
        run: npx prisma generate

      - name: Run tests
        run: npm run test
